### ISSUE TITLE
Key error Succes

### ISSUE THREAD

**Issue by voylin** [wilddom/memrise2anki-extension#52] opened 2017-10-13 12:58 UTC
This is what I get when I'm trying to import a course:

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\********\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\importer.py", line 144, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "C:\Users\********\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 779, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "C:\Users\********\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 579, in loadCourse
    level = self.loadLevel(course, levelIndex)
  File "C:\Users\********\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 640, in loadLevel
    if levelData["success"] == False:
KeyError: 'success'

**Comment by wilddom** [comment] 2017-10-14 09:15
This one is rather old and has beend fixed already.

Duplicate of #47

**Closed by wilddom** 2017-10-14 09:15 UTC
Labels: duplicate

**Comment by voylin** [comment] 2017-10-14 13:10
Yes I know it's old but I keep having it on my PC even after updating everything xs

**Comment by wilddom** [comment] 2017-10-15 07:41
Well, you definitely have an old version, as you can see in issue #47 the code on line 640 has been replaced. But never mind, the current version doesn't work either at the moment.
