### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by v11viktor** [wilddom/memrise2anki-extension#51] opened 2017-09-23 08:13 UTC
Traceback (most recent call last):
  File "C:\Users\Viktor\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\importer.py", line 146, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "C:\Users\Viktor\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 776, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "C:\Users\Viktor\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 579, in loadCourse
    level = self.loadLevel(course, levelIndex)
  File "C:\Users\Viktor\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 647, in loadLevel
    pool = self.loadPool(levelData["pools"][unicode(poolId)])
KeyError: 'pools'

**Comment by wilddom** [comment] 2017-09-23 21:49
Due to a lot of changes on Memrise's side the addon is no longer working. Unfortunately fixing it seems to require quite some work...

Duplicate of #49

**Closed by wilddom** 2017-09-23 21:49 UTC
Labels: duplicate
